quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='main_paginate'),
    path('tag/<str:tag_name>/', views.tag, name='tag'),
    path('search/', views.search, name='search'),
    path('author/<str:author_name>/', views.author_info, name='author'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
]

quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from . import views
from .views import RegisterView
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
]

quotes/quoteapp/models.py
from django.db import models


# Create your models here.
class Authors(models.Model):
    fullname = models.CharField(max_length=100, null=False, unique=True)
    date_born = models.CharField(max_length=100, default='-')
    location_born = models.CharField(max_length=100, default='-')
    bio = models.CharField(default='-')


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quotes(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Authors, on_delete=models.CASCADE, default=None, null=True)
    quote = models.CharField()

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea

from .models import Tag, Authors, Quotes


class AuthorForm(ModelForm):
    fullname = CharField(widget=TextInput(attrs={"class": "form-control"}))
    date_born = CharField(widget=TextInput(attrs={"class": "form-control"}))
    location_born = CharField(widget=TextInput(attrs={"class": "form-control"}))
    bio = CharField(widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Authors
        fields = ['fullname', 'date_born', 'location_born', 'bio']


class QuoteForm(ModelForm):
    quote = CharField(widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Quotes
        fields = ['quote']

quotes/quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q

from .forms import AuthorForm, QuoteForm
from .models import Authors, Tag, Quotes


# Create your views here.
def main(request, page=1):
    """
    The main function is the main page of the website. It displays all quotes,
        and also shows a list of top 10 tags.

    :param request: Get the request object
    :param page: Determine which page of the paginated quotes to display
    :return: The rendered index
    :doc-author: Trelent
    """
    tags_with_count = Tag.objects.annotate(usage_count=Count('quotes'))
    top_10_tags = sorted(tags_with_count, key=lambda x: x.usage_count, reverse=True)[:10]
    quotes = Quotes.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request,
                  'quoteapp/index.html',
                  {"quotes": quotes_on_page,
                   'top_tags': top_10_tags}
                  )


def tag(request, tag_name, page=1):
    """
    The tag function takes a tag_name and page number as arguments. It then gets all the tags with their usage count,
    sorts them in descending order by usage count, and gets the top 10 tags. Then it filters quotes by the given tag
    name, paginates them (10 per page), and returns an index template with those quotes.

    :param request: Get the request object
    :param tag_name: Filter the quotes by tag
    :param page: Get the page number from the url
    :return: A list of quotes that have the tag_name tag
    :doc-author: Trelent
    """
    tags_with_count = Tag.objects.annotate(usage_count=Count('quotes'))
    top_10_tags = sorted(tags_with_count, key=lambda x: x.usage_count, reverse=True)[:10]
    quotes = Quotes.objects.filter(tags__name=tag_name)
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request,
                  'quoteapp/index.html',
                  {"quotes": quotes_on_page,
                   'tag': tag_name,
                   'top_tags': top_10_tags}
                  )


def search(request):
    """
    The search function is responsible for searching the database for quotes, authors and tags.
    It takes a GET request with a query string as an argument and returns the search results page.
    If no query string is provided, it will return all quotes.

    :param request: Get the request object
    :return: A list of quotes that match the query
    :doc-author: Trelent
    """
    query = request.GET.get('q')  # Отримайте рядок запиту з форми
    tags_with_count = Tag.objects.annotate(usage_count=Count('quotes'))
    top_10_tags = sorted(tags_with_count, key=lambda x: x.usage_count, reverse=True)[:10]

    if query:
        # Виконується пошук в вашій моделі Quote
        results = Quotes.objects.filter(
            Q(quote__icontains=query) |  # Пошук за цитатами
            Q(author__fullname__icontains=query) |  # Пошук за ім'ям автора
            Q(tags__name__icontains=query)  # Пошук за тегами
        ).distinct()
    else:
        results = Quotes.objects.all()  # Якщо запит порожній, покаже всі цитати

    return render(request,
                  'quoteapp/search_results.html',
                  {'results': results,
                   'query': query,
                   'top_tags': top_10_tags}
                  )


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/add_author.html', {'form': form})

    return render(request, 'quoteapp/add_author.html', {'form': AuthorForm()})


@login_required
def add_quote(request):
    tags = Tag.objects.all()
    authors = Authors.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            author = Authors.objects.filter(fullname=request.POST.get('author'))[0]
            new_quote.author = author
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/add_quote.html', {"tags": tags, "authors": authors, "form": form})

    return render(request, 'quoteapp/add_quote.html', {"tags": tags, "authors": authors, "form": QuoteForm()})


def author_info(request, author_name):
    author = Authors.objects.get(fullname=author_name)
    return render(request, 'quoteapp/author.html', {'author': author})

quotes/quoteapp/templates/quoteapp/add_author.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>Get author</h1>
<form action="{% url 'quoteapp:add_author' %}" method="post">
  {% csrf_token %}
  <div style="padding: 10px">
      <label> Fullname:
          {{ form.fullname }}
      </label>
      <span>{{ form.errors.fullname }}</span>
  </div>
  <div style="padding: 10px">
      <label> Date born:
          {{ form.date_born }}
      </label>
      <span>{{ form.errors.date_born }}</span>
  </div>
  <div style="padding: 10px">
        <label> Location born:
            {{ form.location_born }}
        </label>
        <span>{{ form.errors.location_born }}</span>
  </div>
  <div style="padding: 10px">
      <label> Biography:
          {{ form.bio }}
      </label>
      <span>{{ form.errors.bio }}</span>
  </div>
  <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/add_quote.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>Add quote</h1>
<form action="{% url 'quoteapp:add_quote' %}" method="post">
  {% csrf_token %}
  <div style="padding: 10px">
      <label> Quote:
          {{ form.quote }}
      </label>
      <span>{{ form.errors.quote }}</span>
  </div>
  <div style="padding: 10px">
        <label> Select author:
            <select class="form-select" name="author">
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select class="form-select" name="tags" multiple="multiple">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/author.html
{% extends 'quoteapp/base.html' %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.date_born }}</span> <span class="author-born-location">{{ author.location_born }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.bio }}
    </div>
</div>
{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
  <header class="header p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'quoteapp:add_author' %}" class="nav-link px-2 link-body-emphasis">Add author</a></li>
          <li><a href="{% url 'quoteapp:add_quote' %}" class="nav-link px-2 link-body-emphasis">Add quote</a></li>
          {% endif %}
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'quoteapp:search' %}" method="get">
            <input type="search" class="form-control" name="q" placeholder="Search..." aria-label="Search">
        </form>

        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ user.profile.avatar.url }}" alt="avatar of user" width="32" height="32" class="rounded-circle" onerror="this.src='../../media/default_avatar.png'">
          </a>
          <ul class="dropdown-menu text-small" style="">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a></li>
              <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
              <li><hr class="dropdown-divider"></li>
              {% endif %}
          </ul>
        </div>
      </div>
      {% block content %}
      {% endblock %}
    </div>
  </header>
</body>
</html>

quotes/quoteapp/templates/quoteapp/index.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div class="row header-box mb-3 mt-3">
    <div class="col-md-8">
        <h1>
            <a href="/" style="text-decoration: none">Quotes</a>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        {% if tag %}
            <h3>Viewing tag: <a href="/tag/{{ tag }}">{{ tag }}</a></h3>
        {% endif %}
        {% for quote in quotes %}
            <div class="card mb-3" style="width: 60rem;">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-body-secondary">{{ quote.author.fullname }}
                    <a href="/author/{{ quote.author.fullname }}">(about)</a>
                    </h6>
                    <p class="card-text">{{ quote.quote }}</p>
                    <div class="tags">
                        Tags:
                        {% for tag in quote.tags.all %}
                            <a class="tag" href="/tag/{{ tag.name }}/">{{tag.name}} | </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-md-3 ms-auto">
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
            <span class="tag-item">
                <a class="tag" style="font-size: {% cycle '28' '26' '26' '24' '22' '14' '10' '8' '8' '6' %}px" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
            </span>
        {% endfor %}
    </div>
</div>

<div class="col-md-8">
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quoteapp:main_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quoteapp:main_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>
        </ul>
    </nav>
</div>

<!--<div class="row header-box mb-3 mt-3">-->
<!--    <div class="col-md-8">-->
<!--        <h1>-->
<!--            <a href="/" style="text-decoration: none">Quotes</a>-->
<!--        </h1>-->
<!--    </div>-->
<!--</div>-->


<!--<div class="row">-->
<!--    <div class="col-md-12 tags-box">-->
<!--        <h2>Top Ten tags</h2>-->
<!--        {% for tag in top_tags %}-->
<!--        <span class="tag-item">-->
<!--            <a class="tag" style="font-size: {% cycle '28' '26' '26' '24' '22' '14' '10' '8' '8' '6' %}px" href="/tag/{{ tag.name }}">{{ tag.name }}</a>-->
<!--            </span>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--    {% if tag %}-->
<!--    <h3>Viewing tag: <a href="/tag/{{ tag }}">{{ tag }}</a></h3>-->
<!--    {% endif %}-->
<!--    {% for quote in quotes %}-->
<!--    <div class="card mb-3" style="width: 60rem;">-->
<!--        <div class="card-body">-->
<!--            <h6 class="card-subtitle mb-2 text-body-secondary">{{ quote.author.fullname }}-->
<!--            <a href="/author/{{ quote.author.fullname }}">(about)</a>-->
<!--            </h6>-->
<!--            <p class="card-text">{{ quote.quote }}</p>-->
<!--            <div class="tags">-->
<!--                Tags:-->
<!--                {% for tag in quote.tags.all %}-->
<!--                <a class="tag" href="/tag/{{ tag.name }}/">{{tag.name}} | </a>-->
<!--                {% endfor %}-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    {% endfor %}-->


<!--    <div class="col-md-8">-->
<!--        <nav>-->
<!--            <ul class="pager">-->

<!--                <li class="previous">-->
<!--                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"-->
<!--                       href="{% if quotes.has_previous %} {% url 'quoteapp:main_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">-->
<!--                        <span aria-hidden="true">←</span> Previous-->
<!--                    </a>-->
<!--                </li>-->


<!--                <li class="next">-->
<!--                    <a class="{% if not quotes.has_next %} disabled {% endif %}"-->
<!--                       href="{% if quotes.has_next %} {% url 'quoteapp:main_paginate' quotes.next_page_number %} {% else %} # {% endif %}">-->
<!--                        Next <span aria-hidden="true">→</span></a>-->
<!--                </li>-->

<!--            </ul>-->
<!--        </nav>-->
<!--    </div>-->
<!--</div>-->



{% endblock %}

<style>
    .top-tags {
        float: right;
        margin-right: 0;
    }

    /* Стилі для заголовку сторінки */
    .header-box h1 {
        text-decoration: none;
    }

    /* Стилі для заголовку "Viewing tag" */
    h3 a {
        text-decoration: none;
    }

    /* Стилі для тегів */
    .tag {
        text-decoration: none;
        color: #007bff;
    }

    /* Стилі для картки цитати */
    .card {
        margin: 10px 0;
    }
</style>

quotes/quoteapp/templates/quoteapp/search_results.html
{% extends "quoteapp/base.html" %}

{% block content %}
  <h1>Search Results</h1>
  <p>You searched for: "{{ query }}"</p>

<!--  {% if results %}-->
<!--    <ul>-->
<!--      {% for quote in results %}-->
<!--        <li>-->
<!--          {{ quote.author.fullname }}: "{{ quote.quote }}"-->
<!--        </li>-->
<!--      {% endfor %}-->
<!--    </ul>-->
<!--  {% else %}-->
<!--    <p>No results found.</p>-->
<!--  {% endif %}-->
<div class="row">
    <div class="col-md-8">
        {% for quote in results %}
            <div class="card mb-3" style="width: 60rem;">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-body-secondary">{{ quote.author.fullname }}
                    <a href="/author/{{ quote.author.fullname }}">(about)</a>
                    </h6>
                    <p class="card-text">{{ quote.quote }}</p>
                    <div class="tags">
                        Tags:
                        {% for tag in quote.tags.all %}
                            <a class="tag" href="/tag/{{ tag.name }}/">{{tag.name}} | </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-md-3 ms-auto">
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
            <span class="tag-item">
                <a class="tag" style="font-size: {% cycle '28' '26' '26' '24' '22' '14' '10' '8' '8' '6' %}px" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
            </span>
        {% endfor %}
    </div>
</div>
{% endblock %}