quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from . import views
from .views import RegisterView
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
]

quotes/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

quotes/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={"class": "form-control", "Placeholder": "First name"}))

    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={"class": "form-control", "Placeholder": "Last name"}))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "Placeholder": "Username"}))
    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={"class": "form-control", "Placeholder": "Email"}))

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={"class": "form-control", "Placeholder": "Password"}))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={"class": "form-control", "Placeholder": "Confirm password"}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control", "Placeholder": "Username"}))

    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "Placeholder": "Password"}))

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

quotes/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm, ProfileForm


# Create your views here.

class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        """
        The dispatch function is a method that gets called when the view is requested. It's responsible for returning
        an HttpResponse object, or raising an exception such as Http404 or PermissionDenied. The dispatch function
        takes in request and args/kwargs parameters, which are passed to it by Django.

        :param self: Represent the instance of the object itself
        :param request: Pass the request object to the view
        :param *args: Pass a variable number of arguments to a function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: A redirect to the main view if a user is logged in
        :doc-author: Trelent
        """
        if request.user.is_authenticated:
            return redirect(to="quoteapp:main")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        """
        The get function is used to display an empty form.
        The get function is called when the user navigates to the URL of this view,
        which in our case will be /contact/.

        :param self: Represent the instance of the object
        :param request: Pass the request object to the view
        :param *args: Pass a non-keyworded, variable-length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: An instance of the form_class
        :doc-author: Trelent
        """
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request, *args, **kwargs):
        """
        The post function is called when the user submits a form.
        The function checks if the form is valid, and if it is, saves it to the database.
        If not, an error message will be displayed on screen.

        :param self: Represent the instance of the class
        :param request: Get the request object
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: A redirect to the login page
        :doc-author: Trelent
        """
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Your account successfully created: {username}")
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


@login_required
def profile(request):
    """
    The profile function is used to render the profile.html template
        when a user visits the /profile/ url.

    :param request: Get the current request
    :return: A rendered template
    :doc-author: Trelent
    """
    return render(request, 'users/profile.html')


@login_required
def profile(request):
    """
    The profile function is used to update the user's profile. It takes a request as an argument and returns a render
    of the users/profile.html template with the profile_form variable passed in.

    :param request: Get the request object
    :return: A profile form
    :doc-author: Trelent
    """
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form})

quotes/users/templates/users/login.html
{% extends "quoteapp/base.html" %}

{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% if form.errors %}
<div class="alert alert-warning" role="alert">
  <span>{{ form.non_field_errors }}</span>
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{form.errors.username}}</span>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
        <span>{{form.errors.password}}</span>
    </div>

    <div class="grid mt-3">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
    <div class="small text-left">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

quotes/users/templates/users/logout.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>Good bye!</h1>
{% endblock %}

quotes/users/templates/users/password_reset.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "quoteapp/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/users/templates/users/profile.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    <h1 class="mt-3">Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-3 mt-3">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid ">
        <button type="submit" class="btn btn-success">Save Changes</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>

</form>

{% endblock content %}

quotes/users/templates/users/register.html
{% extends "quoteapp/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">First name</label>
                        {{ form.first_name}}
                    </div>
                    <span>{{form.errors.first_name}}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Last name</label>
                        {{ form.last_name}}
                    </div>
                    <span>{{form.errors.last_name}}</span>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Username</label>
                        {{ form.username}}
                    </div>
                    <span>{{form.errors.username}}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Email</label>
                        {{ form.email}}
                    </div>
                    <span>{{form.errors.email}}</span>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Password</label>
                        {{ form.password1}}
                    </div>
                    <span>{{form.errors.password1}}</span>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Confirm password</label>
                        {{ form.password2}}
                    </div>
                    <span>{{form.errors.password2}}</span>
                </div>
            </div>
            <div class="form-group mt-4 mb-1">
                <button type="submit" class="btn btn-success">Sign Up</button>
            </div>
        </form>
    </div>

</div>
{% endblock %}